version: "3"

services:
  db:
    image: dct-postgres
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  postgraphile:
    image: graphile/postgraphile
    ports:
      - "5000:5000"
    command:
      [
        "postgraphile",
        "--connection",
        "postgres://postgres:example@db:5432/postgres",
        "--schema",
        "mythgard",
      ]
